[project]
name = "SwMF-LARD-YOLO-ICPR26"
version = "0.1.0"
description = "Project for ICPR 2026 paper experiment on Monitoring Framework for runway detection on LARD using YOLO."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "h5py",
    "ipykernel",
    "kneed",
    "matplotlib",
    "numpy",
    "opencv-python",
    "pandas",
    "plotly",
    "pyproj",
    "scikit-image",
    "scikit-learn",
    "scikit-spatial",
    "scipy",
    "tqdm",
]

[project.optional-dependencies]
cpu = [
    "torch",
    "torchvision",
    "ultralytics",
]
gpu = [
    "torch",
    "torchvision",
    "ultralytics",
]

[dependency-groups]
full = [
    "ipython",
    "onnx",
    "onnxruntime",
    "onnxslim",
    "seaborn",
]

[tool.uv]
conflicts = [
    [
        {extra = "cpu"},
        {extra = "gpu"},
    ]
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-gpu", extra = "gpu" },
]
torchvision = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-gpu", extra = "gpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
